#pragma once
#include <stdint.h>
#include "dict_format.h"

// Dictionary lookup over the two flat files generated by tools/make_dict.py
// (words.idx + defs.dat; record layout in dict_format.h). Hardware-agnostic:
// this module does ALL its file access through the seam below, which each
// build implements once:
//   - web_sim/dict_backend_stdio.cpp  stdio against tools/dict_out
//   - dict_backend_sd.cpp             SD card, firmware-only (excluded from
//                                     the sim build like storage.cpp)
// Keys are normalized before compare exactly like the generator's rule:
// lowercase, keep a-z only ("Ice cream" and "icecream" find the same record).

#define DICT_DISPLAY_LEN 96
#define DICT_MAX_SENSES  16

// All const char* fields point into dict.cpp's internal text buffer and are
// "" (never NULL) when the record has no such field — old-format cards
// ("pos|definition" only) parse with every extra empty.
typedef struct {
  char        pos[4];  // "n" / "v" / "adj" / "adv"
  const char* def;
  const char* ex;      // usage examples, " / "-joined
  const char* syn;     // synonyms, ", "-joined
  const char* ant;     // antonyms, ", "-joined
  const char* kind;    // "type of" parent headword (first hypernym)
} DictSense;

typedef struct {
  char      display[DICT_DISPLAY_LEN];  // defs line 1 ("/"-separated forms)
  int       senseCount;                 // parsed senses (record may hold more)
  DictSense senses[DICT_MAX_SENSES];
} DictEntry;

// ── File-access seam — DECLARED here, implemented by the build's backend ────
// file: 0 = words.idx, 1 = defs.dat. dictReadAt must read exactly len bytes
// at absolute offset off (no partial reads).
bool dictOpen();
bool dictReadAt(int file, uint32_t off, void* buf, uint32_t len);
void dictClose();

// ── Lookup API (dict.cpp) ───────────────────────────────────────────────────
// Opens both files and sanity-checks record 0 and the last record (key
// shape, ordering, defs.dat readability). Idempotent; false = no dictionary
// (missing/bad files) and every call below then fails cleanly.
bool dictInit();

// Close the files and forget init: the next dictInit() (e.g. on dictionary
// open) starts from scratch. Called by dict_update before it overwrites the
// SD files so no stale handle survives the swap.
void dictReset();

// Exact lookup of a normalized key. Returns the record index, or -1.
int dictExact(const char* key);

// Lower/upper-bound binary search for all keys starting with prefix — no
// bucket table. *first = index of the first match, *count = matches (0 if
// none; *first is then the insertion point).
void dictPrefixRange(const char* prefix, uint32_t* first, uint32_t* count);

// Loads and parses record index. The entry's sense .def pointers reference
// one internal static buffer: valid only until the next dictReadEntry call.
bool dictReadEntry(uint32_t index, DictEntry* out);
