// Generated by tools/make_dict.py from WordNet 3.1 - do NOT
// hand-edit; regenerate there and re-copy the CyberPet/ copy.
// words.idx record: [key: DICT_KEY_LEN bytes, a-z, NUL-padded]
//                   [offset: uint32 LE] [length: uint32 LE]
// DICT_MAX_RECORD_LEN sizes the reader's defs.dat text buffer
// (largest merged entry, e.g. all atomic_number_* collide).
#pragma once
#define DICT_KEY_LEN    64
#define DICT_RECORD_SIZE 72
#define DICT_WORD_COUNT 144971
#define DICT_MAX_RECORD_LEN 21432
