// Auto-generated by tools/gen_sprites.py — do not hand-edit.
// Per-stage sprite geometry, indexed by STAGE_* (egg, blob, creature,
// evolved). Canvases are trimmed to the art (no transparent padding), so
// the widget size and the eye anchor (TV-screen center, px from the
// canvas top-left) come from here. grid = art pixel scale (eye snap),
// eyeW/eyeOffX/drift = eye sizing tuned to the screen at that scale.
#pragma once
typedef struct { int w, h, eyeCx, eyeCy, grid, eyeW, eyeOffX, drift; } SpriteLayout;
static const SpriteLayout SPRITE_LAYOUT[4] = {
  { 48, 80, 24, 32, 4, 5, 4, 2 },  // egg,
  { 80, 156, 40, 58, 4, 10, 8, 4 },  // blob,
  { 100, 195, 50, 72, 5, 12, 10, 5 },  // creature,
  { 120, 234, 60, 87, 6, 15, 12, 6 },  // evolved
};
