#!/usr/bin/env python3
"""Regenerates CyberPet/sprites.c + sprites.h — pixel-art body sprites,
one per evolution stage, plus PNG->LVGL-v8 C array conversion.

Sprites are bodies only (no eyes): the firmware's animated eyes render on
top. Sizes must match stageSize() in ui.cpp (80/110/140/170 px).
Output format: LV_IMG_CF_TRUE_COLOR_ALPHA, 16-bit, LV_COLOR_16_SWAP=1.

Usage: python3 tools/gen_sprites.py   (from the repo root; needs Pillow)
Then copy sprites.c/h to CyberPet_1_75B/ and rebuild.
"""
# NOTE: the drawing code below is the July 2026 original; tweak shapes here.
import math, os
from PIL import Image

OUT, SH, HI, LN = 1, 2, 3, 4
PAL = {1:(150,97,62,255), 2:(66,120,235,255), 3:(150,97,62,255), 4:(92,56,36,255), 5:(255,208,96,255)}  # body brown, shade blue, outline dark brown, 5=gold
GOLD = 5

def ellipse(g, cx, cy, rx, ry, v=OUT):
    h, w = len(g), len(g[0])
    for y in range(h):
        for x in range(w):
            if ((x-cx)/rx)**2 + ((y-cy)/ry)**2 <= 1.0: g[y][x] = v

def outline_and_shade(g, shade_from=0.7):
    h, w = len(g), len(g[0])
    o = [row[:] for row in g]
    ys = [y for y in range(h) if any(g[y])]
    y0, y1 = min(ys), max(ys)
    for y in range(h):
        for x in range(w):
            if g[y][x]:
                edge = any(not (0<=y+dy<h and 0<=x+dx<w and g[y+dy][x+dx])
                           for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)))
                if edge: o[y][x] = LN
                elif (y-y0)/(y1-y0+1e-9) > shade_from: o[y][x] = SH
    return o

def render(g, px, canvas):
    h, w = len(g), len(g[0])
    im = Image.new('RGBA', (w, h), (0,0,0,0))
    for y in range(h):
        for x in range(w):
            if g[y][x]: im.putpixel((x, y), PAL[g[y][x]])
    im = im.resize((w*px, h*px), Image.NEAREST)
    sq = Image.new('RGBA', (canvas, canvas), (0,0,0,0))
    sq.alpha_composite(im, ((canvas-im.size[0])//2, (canvas-im.size[1])//2))
    return sq

def put(g, pts, v=OUT):
    for x, y in pts:
        if 0 <= y < len(g) and 0 <= x < len(g[0]): g[y][x] = v

def make_sprites():
    """Returns [(name, image)] — per legged stage: base (both feet planted),
    walk1 (left foot lifted), walk2 (right foot lifted). The firmware
    alternates walk1/walk2 while gliding so BOTH legs step. Egg: one frame."""
    LIFT = 1.1

    def egg_frame():
        egg = [[0]*16 for _ in range(20)]
        for y in range(20):
            t = y/19.0
            half = 6.8 * math.sin(math.pi * (0.18 + 0.82*t) / 1.18) * (0.72 + 0.28*t)
            for x in range(16):
                if abs(x-7.5) <= half: egg[y][x] = OUT
        egg = outline_and_shade(egg, 0.75)
        put(egg, [(5,6),(6,7),(7,6),(8,7),(9,6),(10,7),(6,8),(8,8)], LN)
        return render(egg, 4, 80)

    def feet_dys(phase):
        return (LIFT if phase == 1 else 0.0, LIFT if phase == 2 else 0.0)

    def blob_frame(phase):
        g = [[0]*22 for _ in range(22)]
        ellipse(g, 10.5, 10, 9.6, 9.2)
        ldy, rdy = feet_dys(phase)
        ellipse(g, 5.5, 19 - ldy, 2.4, 1.6)
        ellipse(g, 15.5, 19 - rdy, 2.4, 1.6)
        return render(outline_and_shade(g), 5, 110)

    def creature_frame(phase):
        g = [[0]*28 for _ in range(28)]
        ellipse(g, 13.5, 15, 9.8, 9.0)
        # arms swing opposite the legs while walking
        ady = 1.0 if phase == 1 else (-1.0 if phase == 2 else 0.0)
        ellipse(g, 2.9, 15 + ady, 2.2, 1.5)
        ellipse(g, 24.1, 15 - ady, 2.2, 1.5)
        ldy, rdy = feet_dys(phase)
        ellipse(g, 9.5, 25 - ldy, 2.4, 1.6)
        ellipse(g, 17.5, 25 - rdy, 2.4, 1.6)
        put(g, [(13,5),(13,4),(13,3),(12,2),(14,2),(12,1),(14,1),(13,2)])
        return render(outline_and_shade(g), 5, 140)

    def evolved_frame(phase):
        g = [[0]*34 for _ in range(34)]
        ellipse(g, 16.5, 19, 11.6, 10.6)
        # arms HANG DOWN at the sides and swing opposite the legs
        ady = 1.0 if phase == 1 else (-1.0 if phase == 2 else 0.0)
        ellipse(g, 4.2, 21 + ady, 2.0, 3.2)
        ellipse(g, 28.8, 21 - ady, 2.0, 3.2)
        ldy, rdy = feet_dys(phase)
        ellipse(g, 12.5, 30 - ldy, 2.6, 1.7)
        ellipse(g, 20.5, 30 - rdy, 2.6, 1.7)
        g = outline_and_shade(g)
        # gold crown painted AFTER outline/shade so the thin spikes stay pure
        # gold (the outline pass converts every 1px-wide mark to outline color)
        for x0 in (11, 16, 21):
            put(g, [(x0,8),(x0,7),(x0-1,8),(x0+1,8),(x0,6)], GOLD)
        put(g, [(x,9) for x in range(10,24)], GOLD)
        return render(g, 5, 170)

    out = [('egg', egg_frame())]
    for name, fn in [('blob', blob_frame), ('creature', creature_frame), ('evolved', evolved_frame)]:
        out.append((name, fn(0)))
        out.append((f'{name}_walk1', fn(1)))
        out.append((f'{name}_walk2', fn(2)))
    return out

def to_c(sprites, cpath, hpath):
    out = ['// Auto-generated by tools/gen_sprites.py — do not hand-edit.',
           '// Format: LV_IMG_CF_TRUE_COLOR_ALPHA, 16-bit color, LV_COLOR_16_SWAP=1.',
           '#include "sprites.h"', '']
    for n, im in sprites:
        w, h = im.size
        b = bytearray()
        for y in range(h):
            for x in range(w):
                r, g, bl, a = im.getpixel((x, y))
                c = ((r >> 3) << 11) | ((g >> 2) << 5) | (bl >> 3)
                b += bytes(((c >> 8) & 0xFF, c & 0xFF, a))
        out.append(f'static const uint8_t sprite_{n}_map[] = {{')
        for i in range(0, len(b), 24):
            out.append('  ' + ','.join(f'0x{v:02x}' for v in b[i:i+24]) + ',')
        out.append('};')
        out.append(f'''const lv_img_dsc_t sprite_{n} = {{
  .header = {{ .cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .always_zero = 0, .reserved = 0, .w = {w}, .h = {h} }},
  .data_size = sizeof(sprite_{n}_map),
  .data = sprite_{n}_map,
}};
''')
    open(cpath, 'w').write('\n'.join(out))

if __name__ == '__main__':
    root = os.path.join(os.path.dirname(__file__), '..')
    sprites = make_sprites()
    to_c(sprites, os.path.join(root, 'CyberPet', 'sprites.c'),
         os.path.join(root, 'CyberPet', 'sprites.h'))
    print('wrote CyberPet/sprites.c (sprites.h is hand-maintained)')
