#!/usr/bin/env python3
"""Regenerates CyberPet/sprites.c + sprites.h — pixel-art body sprites,
one per evolution stage, plus PNG->LVGL-v8 C array conversion.

Sprites are bodies only (no eyes): the firmware's animated eyes render on
top. Sizes must match stageSize() in ui.cpp (80/110/140/170 px).
Output format: LV_IMG_CF_TRUE_COLOR_ALPHA, 16-bit, LV_COLOR_16_SWAP=1.

Usage: python3 tools/gen_sprites.py   (from the repo root; needs Pillow)
Then copy sprites.c/h to CyberPet_1_75B/ and rebuild.
"""
# NOTE: the drawing code below is the July 2026 original; tweak shapes here.
import math, os
from PIL import Image

OUT, SH, HI, LN = 1, 2, 3, 4
PAL = {1:(255,255,255,255), 2:(205,210,222,255), 3:(255,255,255,255), 4:(150,158,175,255)}

def ellipse(g, cx, cy, rx, ry, v=OUT):
    h, w = len(g), len(g[0])
    for y in range(h):
        for x in range(w):
            if ((x-cx)/rx)**2 + ((y-cy)/ry)**2 <= 1.0: g[y][x] = v

def outline_and_shade(g, shade_from=0.7):
    h, w = len(g), len(g[0])
    o = [row[:] for row in g]
    ys = [y for y in range(h) if any(g[y])]
    y0, y1 = min(ys), max(ys)
    for y in range(h):
        for x in range(w):
            if g[y][x]:
                edge = any(not (0<=y+dy<h and 0<=x+dx<w and g[y+dy][x+dx])
                           for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)))
                if edge: o[y][x] = LN
                elif (y-y0)/(y1-y0+1e-9) > shade_from: o[y][x] = SH
    return o

def render(g, px, canvas):
    h, w = len(g), len(g[0])
    im = Image.new('RGBA', (w, h), (0,0,0,0))
    for y in range(h):
        for x in range(w):
            if g[y][x]: im.putpixel((x, y), PAL[g[y][x]])
    im = im.resize((w*px, h*px), Image.NEAREST)
    sq = Image.new('RGBA', (canvas, canvas), (0,0,0,0))
    sq.alpha_composite(im, ((canvas-im.size[0])//2, (canvas-im.size[1])//2))
    return sq

def put(g, pts, v=OUT):
    for x, y in pts:
        if 0 <= y < len(g) and 0 <= x < len(g[0]): g[y][x] = v

def make_sprites():
    egg = [[0]*16 for _ in range(20)]
    for y in range(20):
        t = y/19.0
        half = 6.8 * math.sin(math.pi * (0.18 + 0.82*t) / 1.18) * (0.72 + 0.28*t)
        for x in range(16):
            if abs(x-7.5) <= half: egg[y][x] = OUT
    egg = outline_and_shade(egg, 0.75)
    put(egg, [(5,6),(6,7),(7,6),(8,7),(9,6),(10,7),(6,8),(8,8)], LN)

    blob = [[0]*22 for _ in range(22)]
    ellipse(blob, 10.5, 10, 9.6, 9.2)
    ellipse(blob, 5.5, 19, 2.4, 1.6); ellipse(blob, 15.5, 19, 2.4, 1.6)
    blob = outline_and_shade(blob)

    cre = [[0]*28 for _ in range(28)]
    ellipse(cre, 13.5, 15, 9.8, 9.0)
    ellipse(cre, 2.9, 15, 2.2, 1.5); ellipse(cre, 24.1, 15, 2.2, 1.5)
    ellipse(cre, 9.5, 25, 2.4, 1.6); ellipse(cre, 17.5, 25, 2.4, 1.6)
    put(cre, [(13,5),(13,4),(13,3),(12,2),(14,2),(12,1),(14,1),(13,2)])
    cre = outline_and_shade(cre)

    evo = [[0]*34 for _ in range(34)]
    ellipse(evo, 16.5, 19, 11.6, 10.6)
    for x0 in (11, 16, 21):
        put(evo, [(x0,8),(x0,7),(x0-1,8),(x0+1,8),(x0,6)])
    put(evo, [(x,9) for x in range(10,24)])
    ellipse(evo, 3.2, 17, 2.8, 3.6); ellipse(evo, 29.8, 17, 2.8, 3.6)
    ellipse(evo, 12.5, 30, 2.6, 1.7); ellipse(evo, 20.5, 30, 2.6, 1.7)
    evo = outline_and_shade(evo)

    return [('egg', render(egg, 4, 80)), ('blob', render(blob, 5, 110)),
            ('creature', render(cre, 5, 140)), ('evolved', render(evo, 5, 170))]

def to_c(sprites, cpath, hpath):
    out = ['// Auto-generated by tools/gen_sprites.py — do not hand-edit.',
           '// Format: LV_IMG_CF_TRUE_COLOR_ALPHA, 16-bit color, LV_COLOR_16_SWAP=1.',
           '#include "sprites.h"', '']
    for n, im in sprites:
        w, h = im.size
        b = bytearray()
        for y in range(h):
            for x in range(w):
                r, g, bl, a = im.getpixel((x, y))
                c = ((r >> 3) << 11) | ((g >> 2) << 5) | (bl >> 3)
                b += bytes(((c >> 8) & 0xFF, c & 0xFF, a))
        out.append(f'static const uint8_t sprite_{n}_map[] = {{')
        for i in range(0, len(b), 24):
            out.append('  ' + ','.join(f'0x{v:02x}' for v in b[i:i+24]) + ',')
        out.append('};')
        out.append(f'''const lv_img_dsc_t sprite_{n} = {{
  .header = {{ .cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .always_zero = 0, .reserved = 0, .w = {w}, .h = {h} }},
  .data_size = sizeof(sprite_{n}_map),
  .data = sprite_{n}_map,
}};
''')
    open(cpath, 'w').write('\n'.join(out))

if __name__ == '__main__':
    root = os.path.join(os.path.dirname(__file__), '..')
    sprites = make_sprites()
    to_c(sprites, os.path.join(root, 'CyberPet', 'sprites.c'),
         os.path.join(root, 'CyberPet', 'sprites.h'))
    print('wrote CyberPet/sprites.c (sprites.h is hand-maintained)')
